# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: search
  name: kafka-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kafka-manager
  template:
    metadata:
      namespace: search
      labels:
        app: kafka-manager
    spec:
      containers:
      - env:
        - name: ZK_HOSTS
          value: "zoo-0.zoo-hs.search.svc.cluster.local:2181,zoo-1.zoo-hs.search.svc.cluster.local:2181,zoo-2.zoo-hs.search.svc.cluster.local:2181"
        image: hlebalbau/kafka-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: "0.1"
            memory: "1Gi"
          limits:
            cpu: "0.2"
            memory: "2Gi"
        name: kafka-manager
      restartPolicy: Always