apiVersion: v1
kind: List
items:

- apiVersion: v1
  kind: Namespace
  metadata:
    name: chains

- apiVersion: v1
  kind: Namespace
  metadata:
    name: monitoring

- apiVersion: v1
  kind: Namespace
  metadata:
    name: markets

- apiVersion: v1
  kind: Namespace
  metadata:
    name: search

- apiVersion: v1
  kind: Namespace
  metadata:
    name: browser

