{
 "title": "Ethereum Dump",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Last Dumped Tx Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\",topic=\"ETHEREUM_TX_PUMP\"})",
     "legendFormat": "Current Dump Tx Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_TX_PUMP\"})",
     "legendFormat": "Last Dump Tx Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_TX_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\",topic=\"ETHEREUM_TX_PUMP\"})"
    }
   ]
  },
  {
   "title": "Last Dumped Uncle Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-uncles-dump-process\",topic=\"ETHEREUM_UNCLE_PUMP\"})",
     "legendFormat": "Current Dump Uncle Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_UNCLE_PUMP\"})",
     "legendFormat": "Last Uncle Offset"
    }
   ]
  },
  {
   "title": "Last Dumped Block Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-blocks-dump-process\",topic=\"ETHEREUM_BLOCK_PUMP\"})",
     "legendFormat": "Current Dump Block Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_BLOCK_PUMP\"})",
     "legendFormat": "Last Block Offset"
    }
   ]
  }
 ]
}