{
 "title": "Ethereum Contract Summary",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Updates per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "500 * rate(contract_summary_commit_kafka_seconds_count[10s])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Last Applied Tx Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(contract_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"})",
     "legendFormat": "Ethereum Txs Contract Summary Processed Offsets"
    },
    {
     "expr": "sum(pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"})",
     "legendFormat": "Ethereum Txs Contract Summary Last Offset"
    }
   ]
  },
  {
   "title": "Last Applied Block Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(contract_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"})",
     "legendFormat": "Current Contract Summary Block Offset"
    },
    {
     "expr": "sum(pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"})",
     "legendFormat": "Last Contract Summary Ethereum Block Offset"
    }
   ]
  },
  {
   "title": "Last Applied Uncle Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(contract_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"})",
     "legendFormat": "Current Contract Summary Uncle Offset"
    },
    {
     "expr": "sum(pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"})",
     "legendFormat": "Last Contract Summary Uncle Offset"
    }
   ]
  },
  {
   "title": "Apply Tx Locks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(contract_summary_apply_lock_counter_total{chain=\"ETHEREUM\", topic=\"ETHEREUM_TX_PUMP\"})"
    }
   ]
  },
  {
   "title": "Apply Block Locks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(contract_summary_apply_lock_counter_total{chain=\"ETHEREUM\", topic=\"ETHEREUM_BLOCK_PUMP\"})"
    }
   ]
  },
  {
   "title": "Apply Uncle Locks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(contract_summary_apply_lock_counter_total{chain=\"ETHEREUM\", topic=\"ETHEREUM_UNCLE_PUMP\"})"
    }
   ]
  },
  {
   "title": "Tx Offsets To Apply Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"}) - sum(contract_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"})",
     "legendFormat": "Tx Offsets To Apply Remaining"
    }
   ]
  },
  {
   "title": "Block Offsets To Apply Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"}) - sum(contract_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"})",
     "legendFormat": "Block Offsets To Apply Remaining"
    }
   ]
  },
  {
   "title": "Uncle Offsets To Apply Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"}) - sum(contract_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"})",
     "legendFormat": "Uncle Offsets To Apply Remaining"
    }
   ]
  },
  {
   "title": "Contract Summary Download Cassandra Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_download_cassandra_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(contract_summary_download_cassandra_seconds_count{chain=\"ETHEREUM\"}[1m])) by (topic)",
     "legendFormat": "Contract Summary Download Cassandra Time {{topic}}"
    }
   ]
  },
  {
   "title": "Contract Summary Commit Kafka Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_commit_kafka_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(contract_summary_commit_kafka_seconds_count{chain=\"ETHEREUM\"}[1m])) by (topic)",
     "legendFormat": "Contract Summary Commit Kafka Time {{topic}}"
    }
   ]
  },
  {
   "title": "Contract Delta Store Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_delta_store_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(contract_summary_delta_store_seconds_count{chain=\"ETHEREUM\"}[1m])) by (topic)",
     "legendFormat": "Contract Delta Store TIme {{topic}}"
    }
   ]
  },
  {
   "title": "Contract Summary Commit Cassandra Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_commit_cassandra_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(contract_summary_commit_cassandra_seconds_count{chain=\"ETHEREUM\"}[1m])) by (topic)",
     "legendFormat": "Contract Summary Commit Cassandra Time {{topic}}"
    }
   ]
  }
 ]
}