{
 "title": "Orderbooks",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Orders count(24h)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(orderbook_size[24h]))"
    }
   ]
  },
  {
   "title": "Orders count by Exchange",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(orderbook_size) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "OrderBook size by tokens pair",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(orderbook_size) by (tokens_pair)",
     "legendFormat": "{{tokens_pair}}"
    }
   ]
  },
  {
   "title": "OrderBook size",
   "type": "table",
   "gridPos": { "h": 9, "w": 11, "x": 6, "y": 23 },
   "targets": [
    {
     "expr": "sum(orderbook_size) by (exchange, tokens_pair, order_type)",
     "legendFormat": "Exchange: {{exchange}}; Pair: {{tokens_pair}}; Type: {{order_type}}"
    }
   ]
  }
 ]
}