{
 "title": "Trades",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15s",
 "panels": [
  {
   "title": "Trades count (24h)",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 6, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(trade_count_total[24h]))"
    }
   ]
  },
  {
   "title": "Trades per second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(trade_count_total[1m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Trade latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(trade_latency_seconds) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Trade count by Token",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(trade_count_by_token_total[5m])) by (token)",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "Trades count by tokens pair",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(trade_count_total[5m])) by (tokens_pair)",
     "legendFormat": "{{tokens_pair}}"
    }
   ]
  }
 ]
}