{
 "title": "Bitcoin Indexation",
 "tags": [ "chain" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "chainName",
    "label": "Chain",
    "query": "label_values(pump_last_processed_block{chainFamily=\"BITCOIN\"}, chainName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Last Indexed Block",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 0 },
   "format": "locale",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(pump_last_processed_block{chainFamily=\"BITCOIN\", chainName=\"$chainName\"})"
    }
   ]
  },
  {
   "title": "Mempool Txes 1h",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 7, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(delta(mempool_tx_counter_total{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1h]))"
    }
   ]
  },
  {
   "title": "Dump Block Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 10, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"${chainName}_BLOCK_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"dump-process\",topic=\"${chainName}_BLOCK_PUMP\"})"
    }
   ]
  },
  {
   "title": "Dump Tx Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 13, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"${chainName}_TX_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"dump-process\",topic=\"${chainName}_TX_PUMP\"})"
    }
   ]
  },
  {
   "title": "Contract Tx Queue",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 16, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"${chainName}_TX_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"contract-summary-update-process\",topic=\"${chainName}_TX_PUMP\"})"
    }
   ]
  },
  {
   "title": "Mined Blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "sum(idelta(pump_last_network_block{chainFamily=\"BITCOIN\", chainName=~\"$chainName\"}[30s]))"
    }
   ]
  },
  {
   "title": "New Mempool Txes",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(idelta(mempool_tx_counter_total{chainFamily=\"BITCOIN\", chainName=~\"$chainName\"}[1m]))"
    }
   ]
  },
  {
   "title": "Pump",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last Pumped Block",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "yaxes": [
      { "format": "locale" }
     ],
     "targets": [
      {
       "expr": "sum(pump_last_processed_block{chainFamily=\"BITCOIN\", chainName=\"$chainName\"})",
       "legendFormat": "Indexed Block"
      },
      {
       "expr": "sum(pump_last_network_block{chainFamily=\"BITCOIN\", chainName=\"$chainName\"})",
       "legendFormat": "Network Block"
      }
     ]
    },
    {
     "title": "Outputs Cache Usage",
     "type": "graph",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 10 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(total_linked_outputs{chainFamily=\"BITCOIN\", chainName=\"$chainName\"})",
       "legendFormat": "Total Linked Outputs"
      },
      {
       "expr": "sum(linked_outputs_from_cache{chainFamily=\"BITCOIN\", chainName=\"$chainName\"})",
       "legendFormat": "Linked Outputs From Cache"
      },
      {
       "expr": "sum_over_time(linked_outputs_from_cache{chainFamily=\"BITCOIN\", chainName=~\"$chainName\"}[1h]) / sum_over_time(total_linked_outputs{chainFamily=\"BITCOIN\", chainName=~\"$chainName\"}[1h])",
       "legendFormat": "Cache Hit Rage"
      }
     ]
    },
    {
     "title": "Get Bitcoin Block REST Request time",
     "type": "graph",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 10 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(sum_over_time(bitcoin_block_request_seconds_sum{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m])/sum_over_time(bitcoin_block_request_seconds_count{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m]))",
       "legendFormat": "Request Time"
      }
     ]
    },
    {
     "title": "Blocks Per Second",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 17 },
     "yaxes": [
      { "format": "locale", "label": "block/sec" }
     ],
     "targets": [
      {
       "expr": "sum(rate(pump_last_processed_block{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[10m]))"
      }
     ]
    },
    {
     "title": "Block download speed",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 17 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "sum(sum_over_time(pump_bundle_download_seconds_sum{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m])/sum_over_time(pump_bundle_download_seconds_count{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m]))",
       "legendFormat": "Single Block Download Time"
      },
      {
       "expr": "sum(sum_over_time(pump_bundle_kafka_store_seconds_sum{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m])/sum_over_time(pump_bundle_kafka_store_seconds_count{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m]))",
       "legendFormat": "Kafka Transaction Batch Store Time"
      }
     ]
    },
    {
     "title": "Cache size",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 9, "y": 19 },
     "format": "decbytes",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(txs_outputs_cache_size_bytes{chainFamily=\"BITCOIN\", chainName=\"$chainName\"})"
      }
     ]
    },
    {
     "title": "Cache items count",
     "type": "singlestat",
     "gridPos": { "h": 3, "w": 3, "x": 12, "y": 19 },
     "format": "none",
     "valueName": "current",
     "targets": [
      {
       "expr": "sum(txs_outputs_cache_items{chainFamily=\"BITCOIN\", chainName=\"$chainName\"})"
      }
     ]
    }
   ]
  },
  { "title": "Dump", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Last Dumped Tx Offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"dump-process\",topic=\"${chainName}_TX_PUMP\"})",
     "legendFormat": "Dumped Tx Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"${chainName}_TX_PUMP\"})",
     "legendFormat": "LastTx Offset"
    }
   ]
  },
  {
   "title": "Dump Records Per Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{consumergroup=\"dump-process\", topic=\"${chainName}_TX_PUMP\"}[1h]))",
     "legendFormat": "Tx Records"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{consumergroup=\"dump-process\", topic=\"${chainName}_BLOCK_PUMP\"}[1h]))",
     "legendFormat": "Block Records"
    }
   ]
  },
  {
   "title": "Last Dumped Block Offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"dump-process\",topic=\"${chainName}_BLOCK_PUMP\"})",
     "legendFormat": "Dumped Block Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"${chainName}_BLOCK_PUMP\"})",
     "legendFormat": "Last Block Offset"
    }
   ]
  },
  { "title": "Contract Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Last Applied Tx Offset",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"contract-summary-update-process\",topic=\"${chainName}_TX_PUMP\"})",
     "legendFormat": " Txes Applied Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"${chainName}_TX_PUMP\"})",
     "legendFormat": " Txes Last Offset"
    }
   ]
  },
  {
   "title": "Updates per seconds",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 25 },
   "yaxes": [
    { "format": "wps", "label": "Offsets/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{consumergroup=\"contract-summary-update-process\", topic=\"${chainName}_TX_PUMP\"}[1m])) by (topic)",
     "legendFormat": "[1m] {{topic}}"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{consumergroup=\"contract-summary-update-process\", topic=\"${chainName}_TX_PUMP\"}[1h])) by (topic)",
     "legendFormat": "[1h] {{topic}}"
    }
   ]
  },
  {
   "title": "Contract Summary Process Steps Times",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 25 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_download_cassandra_seconds_sum{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m])/sum_over_time(contract_summary_download_cassandra_seconds_count{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m]))",
     "legendFormat": "Download Cassandra Time"
    },
    {
     "expr": "sum(sum_over_time(contract_summary_delta_store_seconds_sum{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m])/sum_over_time(contract_summary_delta_store_seconds_count{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m]))",
     "legendFormat": "Apply  Delta Time"
    },
    {
     "expr": "sum(sum_over_time(contract_summary_commit_kafka_seconds_sum{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m])/sum_over_time(contract_summary_commit_kafka_seconds_count{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m]))",
     "legendFormat": "Kafka Commit Time"
    },
    {
     "expr": "sum(sum_over_time(contract_summary_commit_cassandra_seconds_sum{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m])/sum_over_time(contract_summary_commit_cassandra_seconds_count{chainFamily=\"BITCOIN\", chainName=\"$chainName\"}[1m]))",
     "legendFormat": "CS Commit Time"
    }
   ]
  }
 ]
}