{
 "title": "Ethereum Classic Dump",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Txs Offsets Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_TX_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\",topic=\"ETHEREUM_CLASSIC_TX_PUMP\"})"
    }
   ]
  },
  {
   "title": "Tx Dump Remaining Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_TX_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\", topic=\"ETHEREUM_CLASSIC_TX_PUMP\"})) / sum(rate(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\", topic=\"ETHEREUM_CLASSIC_TX_PUMP\"}[10m]))"
    }
   ]
  },
  {
   "title": "Blocks Offsets Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-blocks-dump-process\",topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"})"
    }
   ]
  },
  {
   "title": "Block Dump Remaining Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-blocks-dump-process\", topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"})) / sum(rate(kafka_consumergroup_current_offset{consumergroup=\"ethereum-blocks-dump-process\", topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"}[10m]))"
    }
   ]
  },
  {
   "title": "Uncles Offsets Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-uncles-dump-process\",topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"})"
    }
   ]
  },
  {
   "title": "Uncle Dump Remaining Time",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "(sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-uncles-dump-process\", topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"})) / sum(rate(kafka_consumergroup_current_offset{consumergroup=\"ethereum-uncles-dump-process\", topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"}[10m]))"
    }
   ]
  },
  {
   "title": "Last Dumped Tx Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\",topic=\"ETHEREUM_CLASSIC_TX_PUMP\"})",
     "legendFormat": "Current Dump Tx Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_TX_PUMP\"})",
     "legendFormat": "Last Dump Tx Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_TX_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\",topic=\"ETHEREUM_CLASSIC_TX_PUMP\"})"
    }
   ]
  },
  {
   "title": "Last Dumped Block Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-blocks-dump-process\",topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"})",
     "legendFormat": "Current Dump Block Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"})",
     "legendFormat": "Last Block Offset"
    }
   ]
  },
  {
   "title": "Last Dumped Uncle Offset",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"ethereum-uncles-dump-process\",topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"})",
     "legendFormat": "Current Dump Uncle Offset"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"})",
     "legendFormat": "Last Uncle Offset"
    }
   ]
  },
  {
   "title": "Dump Records Per Second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(kafka_consumergroup_current_offset{consumergroup=\"ethereum-txs-dump-process\", topic=\"ETHEREUM_CLASSIC_TX_PUMP\"}[1h])",
     "legendFormat": "Transaction Per Second"
    },
    {
     "expr": "rate(kafka_consumergroup_current_offset{consumergroup=\"ethereum-blocks-dump-process\", topic=\"ETHEREUM_CLASSIC_BLOCK_PUMP\"}[1h])",
     "legendFormat": "Blocks Per Second"
    },
    {
     "expr": "rate(kafka_consumergroup_current_offset{consumergroup=\"ethereum-uncles-dump-process\", topic=\"ETHEREUM_CLASSIC_UNCLE_PUMP\"}[1h])",
     "legendFormat": "Uncles Per Second"
    }
   ]
  }
 ]
}