{
 "title": "Bitcoin Contract Summary",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Apply Tx Locks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(contract_summary_apply_lock_counter_total{chain=\"BITCOIN\", topic=\"BITCOIN_TX_PUMP\"})"
    }
   ]
  },
  {
   "title": "Tx Offsets To Apply Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"BITCOIN_TX_PUMP\"}) - sum(kafka_consumergroup_current_offset{consumergroup=\"bitcoin-contract-summary-update-process\",topic=\"BITCOIN_TX_PUMP\"})",
     "legendFormat": "Tx Offsets To Apply Remaining"
    }
   ]
  },
  {
   "title": "Updates per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "wps", "label": "Offsets/sec" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{consumergroup=\"bitcoin-contract-summary-update-process\", topic=\"BITCOIN_TX_PUMP\"}[1m])) by (topic)",
     "legendFormat": "[1m] {{topic}}"
    },
    {
     "expr": "sum(rate(kafka_consumergroup_current_offset{consumergroup=\"bitcoin-contract-summary-update-process\", topic=\"BITCOIN_TX_PUMP\"}[1h])) by (topic)",
     "legendFormat": "[1h] {{topic}}"
    }
   ]
  },
  {
   "title": "Last Applied Tx Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_current_offset{consumergroup=\"bitcoin-contract-summary-update-process\",topic=\"BITCOIN_TX_PUMP\"})",
     "legendFormat": "Bitcoin Txs Contract Summary Processed Offsets"
    },
    {
     "expr": "sum(kafka_topic_partition_current_offset{topic=\"BITCOIN_TX_PUMP\"})",
     "legendFormat": "Bitcoin Txs Contract Summary Last Offset"
    }
   ]
  },
  {
   "title": "Contract Summary Download Cassandra Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_download_cassandra_seconds_sum{chain=\"BITCOIN\"}[1m])/sum_over_time(contract_summary_download_cassandra_seconds_count{chain=\"BITCOIN\"}[1m])) by (topic)",
     "legendFormat": "Contract Summary Download Cassandra Time {{topic}}"
    }
   ]
  },
  {
   "title": "Contract Summary Commit Kafka Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_commit_kafka_seconds_sum{chain=\"BITCOIN\"}[1m])/sum_over_time(contract_summary_commit_kafka_seconds_count{chain=\"BITCOIN\"}[1m])) by (topic)",
     "legendFormat": "Contract Summary Commit Kafka Time {{topic}}"
    }
   ]
  },
  {
   "title": "Contract Delta Store Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_delta_store_seconds_sum{chain=\"BITCOIN\"}[1m])/sum_over_time(contract_summary_delta_store_seconds_count{chain=\"BITCOIN\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Contract Summary Commit Cassandra Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(sum_over_time(contract_summary_commit_cassandra_seconds_sum{chain=\"BITCOIN\"}[1m])/sum_over_time(contract_summary_commit_cassandra_seconds_count{chain=\"BITCOIN\"}[1m])) by (topic)",
     "legendFormat": "Contract Summary Commit Cassandra Time {{topic}}"
    }
   ]
  }
 ]
}