version: "3.8"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    environment:
      - DOMAIN
    ports:
      - "80:80"
      - "443:443"
      - "81:81"
    volumes:
      - ./volumes/nginx/cybernode_init.conf:/etc/nginx/conf.d/cybernode_init.conf
      - ./volumes/nginx/www:/var/www
      - ./volumes/certbot/letsencrypt:/etc/letsencrypt
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    depends_on:
      - nginx
    command: certonly  --cert-name cybernode --reinstall --webroot --webroot-path=/var/www/ --no-eff-email --agree-tos --email ${EMAIL} -d ${DOMAIN} -d rpc.bostrom.${DOMAIN} -d grpc.bostrom.${DOMAIN} -d lcd.bostrom.${DOMAIN} -d ipfs.${DOMAIN}
    volumes:
      - ./volumes/nginx/www/:/var/www/
      - ./volumes/certbot/letsencrypt:/etc/letsencrypt:rw
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: "3"
