global:
  scrape_interval:     15s
  evaluation_interval: 5s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
       - targets: ['prometheus:9090']
#      - targets: ['localhost:36080']
  - job_name: 'node_exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['node-exporter:9100']
  - job_name: 'bostrom'
    scrape_interval: 5s
    static_configs:
      - targets: ['bostrom:26660']
  - job_name: 'cadvisor'
    scrape_interval: 5s
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'ipfs'
#    metrics_path: '/debug/metrics/prometheus'
    scrape_interval: 5s
    static_configs:
       - targets: ['ipfs:36001']
  - job_name: 'cyberindex_postgres'
    scrape_interval: 5s
    static_configs:
      - targets: ['cyberindex_postgres:5432']
  - job_name: 'cyberindex_hasura'
    scrape_interval: 5s
    static_configs:
      - targets: ['cyberindex_hasura:8089']
  - job_name: 'nginx-exporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['172.23.0.1:9113']
