{
 "title": "Ethereum dump",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Last Dumped Tx Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dump_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"}",
     "legendFormat": "Current Dump Tx Offset"
    },
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"}",
     "legendFormat": "Last Tx Offset"
    }
   ]
  },
  {
   "title": "Tx Offsets To Dump Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"} - ignoring(instance)dump_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"}",
     "legendFormat": "Tx Offsets To Dump Remaining"
    }
   ]
  },
  {
   "title": "Block Offsets To Dump Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"} - ignoring(instance)dump_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"}",
     "legendFormat": "Block Offsets To Dump Remaining"
    }
   ]
  },
  {
   "title": "Uncle Offsets To Dump Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"} - ignoring(instance)dump_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"}",
     "legendFormat": "Uncle Offsets To Dump Remaining"
    }
   ]
  },
  {
   "title": "Last Dumped Uncle Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dump_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"}",
     "legendFormat": "Current Dump Uncle Offset"
    },
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"}",
     "legendFormat": "Last Uncle Offset"
    }
   ]
  },
  {
   "title": "Last Dumped Block Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dump_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"}",
     "legendFormat": "Current Dump Block Offset"
    },
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"}",
     "legendFormat": "Last Block Offset"
    }
   ]
  }
 ]
}