{
 "title": "Ethereum address summary",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Address Delta Store Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(address_summary_delta_store_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(address_summary_delta_store_seconds_count{chain=\"ETHEREUM\"}[1m])",
     "legendFormat": "Address Delta Store TIme {{topic}}"
    }
   ]
  },
  {
   "title": "Address Summary Commit Kafka Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(address_summary_commit_kafka_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(address_summary_commit_kafka_seconds_count{chain=\"ETHEREUM\"}[1m])",
     "legendFormat": "Address Summary Commit Kafka Time {{topic}}"
    }
   ]
  },
  {
   "title": "Address Summary Download Cassandra Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "1000 * sum_over_time(address_summary_download_cassandra_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(address_summary_download_cassandra_seconds_count{chain=\"ETHEREUM\"}[1m])",
     "legendFormat": "Address Summary Download Cassandra Time {{topic}}"
    }
   ]
  },
  {
   "title": "Address Summary Commit Cassandra Speed",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum_over_time(address_summary_commit_cassandra_seconds_sum{chain=\"ETHEREUM\"}[1m])/sum_over_time(address_summary_commit_cassandra_seconds_count{chain=\"ETHEREUM\"}[1m])",
     "legendFormat": "Address Summary Commit Cassandra Time {{topic}}"
    }
   ]
  },
  {
   "title": "Apply Tx Locks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "address_summary_apply_lock_counter_total{chain=\"ETHEREUM\", topic=\"ETHEREUM_TX_PUMP\"}"
    }
   ]
  },
  {
   "title": "Apply Block Locks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "address_summary_apply_lock_counter_total{chain=\"ETHEREUM\", topic=\"ETHEREUM_BLOCK_PUMP\"}"
    }
   ]
  },
  {
   "title": "Apply Uncle Locks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "address_summary_apply_lock_counter_total{chain=\"ETHEREUM\", topic=\"ETHEREUM_UNCLE_PUMP\"}"
    }
   ]
  },
  {
   "title": "Tx Offsets To Apply Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"} - ignoring(instance)address_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"}",
     "legendFormat": "Tx Offsets To Apply Remaining"
    }
   ]
  },
  {
   "title": "Block Offsets To Apply Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"} - ignoring(instance)address_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"}",
     "legendFormat": "Block Offsets To Apply Remaining"
    }
   ]
  },
  {
   "title": "Uncle Offsets To Apply Remaining",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"} - ignoring(instance)address_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"}",
     "legendFormat": "Uncle Offsets To Apply Remaining"
    }
   ]
  },
  {
   "title": "Updates per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "wps" }
   ],
   "targets": [
    {
     "expr": "500 * rate(address_summary_commit_kafka_seconds_count[10s])",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Last Applied Uncle Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "address_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"}",
     "legendFormat": "Current Address Summary Uncle Offset"
    },
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_UNCLE_PUMP\"}",
     "legendFormat": "Last Uncle Offset"
    }
   ]
  },
  {
   "title": "Last Applied Block Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "address_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"}",
     "legendFormat": "Current Address Summary Block Offset"
    },
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_BLOCK_PUMP\"}",
     "legendFormat": "Last Ethereum Block Offset"
    }
   ]
  },
  {
   "title": "Last Applied Tx Offset",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 30 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "address_summary_topic_current_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"}",
     "legendFormat": "Ethereum Txs Address Summary Processed Offsets"
    },
    {
     "expr": "pump_topic_last_offset{chain=\"ETHEREUM\",topic=\"ETHEREUM_TX_PUMP\"}",
     "legendFormat": "Ethereum Txs Last Offset"
    }
   ]
  }
 ]
}