{
 "title": "Search Api Statistics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "99.5% Percentile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(http_requests_processing_seconds{quantile=\"0.995\"}) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "95% Percentile",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "avg(http_requests_processing_seconds{quantile=\"0.95\"}) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_processing_seconds_count[10s])) by (uri)",
     "legendFormat": "{{uri}}"
    }
   ]
  },
  {
   "title": "Request per seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "rps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_processing_seconds_count[10s])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}