# Exchanges Connector CEX Service (should expose metrics)
apiVersion: v1
kind: Service
metadata:
  name: exchanges-connector-cex
  namespace: markets
  labels:
    monitoring: default-monitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: exchanges-connector-cex
---

# Exchanges Connector CEX Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: markets
  name: exchanges-connector-cex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: markets
      labels:
        app: exchanges-connector-cex
    spec:
      containers:
      - env:
        - name: CM_LOG_LEVEL
          value: INFO
        - name: KAFKA_BROKERS
          value: kafka-broker.markets:9092
        - name: EXCHANGES
          value: bitfinex,bitflyer,binance,bitstamp,gdax,gemini,hitbtc,okcoin,okex,poloniex
        - name: JAVA_OPTS
          value: -Xms6g -Xmx6g
        image: cybernode/cm-exchanges-connector:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1.5"
            memory: "8Gi"
          limits:
            cpu: "2"
            memory: "8Gi"
        name: exchanges-connector-cex
      restartPolicy: Always