# Exchanges Connector DEX (should expose metrics)
apiVersion: v1
kind: Service
metadata:
  name: exchanges-connector-dex
  namespace: markets
  labels:
    monitoring: default-monitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: exchanges-connector-dex
---

# Exchanges Connector DEX Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: markets
  name: exchanges-connector-dex
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: markets
      labels:
        app: exchanges-connector-dex
    spec:
      containers:
      - env:
        - name: PARITY_URL
          value: http://parity-eth.chains.svc:8545
        - name: CM_LOG_LEVEL
          value: INFO
        - name: KAFKA_BROKERS
          value: kafka-broker.markets:9092
        - name: EXCHANGES
          value: etherdelta
        - name: JAVA_OPTS
          value: -Xms2g -Xmx2g
        image: cybernode/cm-exchanges-connector:latest
        name: exchanges-connector-dex
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "1"
            memory: "3Gi"
          limits:
            cpu: "1.5"
            memory: "3Gi"
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 300
          timeoutSeconds: 3
          periodSeconds: 30
      restartPolicy: Always
