# Datasource ConfigMap for Grafana Watcher
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-datasources
  namespace: monitoring
data:
  prometheus.yaml: |+
    apiVersion: 1
    datasources:
     - name: PROMETHEUS
       type: prometheus
       access: proxy
       org_id: 1
       url: http://prometheus.monitoring.svc:9090
       version: 1
       editable: true
---
# Dashboard Provider ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-dashboards-providers
  namespace: monitoring
data:
  dashboards.yaml: |+
    apiVersion: 1

    providers:
    - name: 'default'
      orgId: 1
      folder: ''
      type: file
      options:
        path: /grafana-dashboards-common
    - name: 'ethereum'
      orgId: 1
      folder: 'Ethereum'
      type: file
      options:
        path: /grafana-dashboards-eth
    - name: 'ethereum_classic'
      orgId: 1
      folder: 'Ethereum Classic'
      type: file
      options:
        path: /grafana-dashboards-etc
    - name: 'bitcoin'
      orgId: 1
      folder: 'Bitcoin'
      type: file
      options:
        path: /grafana-dashboards-btc
    - name: 'exchanges'
      orgId: 1
      folder: 'Exchanges'
      type: file
      options:
        path: /grafana-dashboards-exchanges
---

# Grafana Data Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: monitoring
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---

# Grafana
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: grafana
      namespace: monitoring
    spec:
      containers:
      - name: grafana
        env:
        - name: GF_AUTH_ANONYMOUS_ENABLED
          value: "true"
        - name: GF_AUTH_ANONYMOUS_NAME
          value: "Main Org."
        - name: GF_AUTH_ANONYMOUS_ROLE
          value: "Viewer"
        image: grafana/grafana:5.0.4
        volumeMounts:
        - name: grafana-datasources
          mountPath: /etc/grafana/provisioning/datasources
        - name: grafana-dashboards-providers
          mountPath: /etc/grafana/provisioning/dashboards
        - name: grafana-dashboards-common
          mountPath: /grafana-dashboards-common
        - name: grafana-dashboards-eth
          mountPath: /grafana-dashboards-eth
        - name: grafana-dashboards-etc
          mountPath: /grafana-dashboards-etc
        - name: grafana-dashboards-btc
          mountPath: /grafana-dashboards-btc
        - name: grafana-dashboards-exchanges
          mountPath: /grafana-dashboards-exchanges
        - name: grafana-data
          mountPath: /var/lib/grafana
        ports:
        - name: web
          containerPort: 3000
        resources:
          requests:
            memory: 100Mi
            cpu: 100m
          limits:
            memory: 200Mi
            cpu: 200m
      volumes:
      - name: grafana-datasources
        configMap:
          name: grafana-datasources
      - name: grafana-dashboards-providers
        configMap:
          name: grafana-dashboards-providers
      - name: grafana-dashboards-common
        configMap:
          name: grafana-dashboards-common
      - name: grafana-dashboards-eth
        configMap:
          name: grafana-dashboards-eth
      - name: grafana-dashboards-etc
        configMap:
          name: grafana-dashboards-etc
      - name: grafana-dashboards-btc
        configMap:
          name: grafana-dashboards-btc
      - name: grafana-dashboards-exchanges
        configMap:
          name: grafana-dashboards-exchanges
      - name: grafana-data
        persistentVolumeClaim:
          claimName: grafana-data
---
# Grafana Service
apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
  - name: "web"
    port: 80
    targetPort: 3000
  selector:
    app: grafana