{
 "title": "Chains Overall Indexation",
 "description": "cluster",
 "tags": [ "cluster" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Mined Blocks",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(idelta(pump_last_network_block[30s])) by (chainFamily, chainName)",
     "legendFormat": "{{chainName}}"
    }
   ]
  },
  {
   "title": "Chains Overall",
   "type": "table",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "max(pump_last_processed_block) by (chainFamily, chainName)"
    },
    {
     "expr": "max(pump_last_network_block) by (chainFamily, chainName)"
    },
    {
     "expr": "sum(delta(pump_last_processed_block[24h])) by (chainFamily, chainName)"
    },
    {
     "expr": "sum(label_replace(delta(kafka_topic_partition_current_offset{topic=~\".*_TX_PUMP\"}[24h]),\"chainName\", \"$1\", \"topic\", \"(.*?)_TX_PUMP\")) by (chainName)"
    },
    {
     "expr": "avg(pump_bundle_download_seconds_sum) by (chainFamily, chainName) / avg(pump_bundle_download_seconds_count) by (chainFamily, chainName)"
    },
    {
     "expr": "sum(label_replace(kafka_topic_partition_current_offset{topic=~\".*_(BLOCK|UNCLE)_PUMP\"},\"chainName\", \"$1\", \"topic\", \"(.*?)_BLOCK_PUMP\")) by (chainName) - sum(label_replace(kafka_consumergroup_current_offset{topic=~\".*_(BLOCK|UNCLE)_PUMP\",consumergroup=\"dump-process-group\"},\"chainName\", \"$1\", \"topic\", \"(.*?)_BLOCK_PUMP\")) by (chainName)"
    },
    {
     "expr": "sum(label_replace(kafka_topic_partition_current_offset{topic=~\".*_TX_PUMP\"},\"chainName\", \"$1\", \"topic\", \"(.*?)_TX_PUMP\")) by (chainName) - sum(label_replace(kafka_consumergroup_current_offset{topic=~\".*_TX_PUMP\",consumergroup=\"dump-process-group\"},\"chainName\", \"$1\", \"topic\", \"(.*?)_TX_PUMP\")) by (chainName)"
    },
    {
     "expr": "sum(label_replace(kafka_topic_partition_current_offset{topic=~\".*_TX_PUMP\"},\"chainName\", \"$1\", \"topic\", \"(.*?)_TX_PUMP\")) by (chainName) - sum(label_replace(kafka_consumergroup_current_offset{topic=~\".*_TX_PUMP\",consumergroup=\"contract-summary-update-process-group\"},\"chainName\", \"$1\", \"topic\", \"(.*?)_TX_PUMP\")) by (chainName)"
    },
    {
     "expr": "sum(delta(mempool_tx_counter_total[10m])) by (chainFamily, chainName)"
    },
    {
     "expr": "sum(  sum_over_time(dump_process_tx_latency_seconds_sum[1h]) / sum_over_time(dump_process_tx_latency_seconds_count[1h])  ) by (chainFamily, chainName)"
    }
   ]
  },
  {
   "title": "Chains Index",
   "type": "table",
   "gridPos": { "h": 5, "w": 12, "x": 6, "y": 12 },
   "targets": [
    {
     "expr": "sum(label_replace(elasticsearch_indices_docs_primary{namespace=\"search\", index=~\".*.tx\"}, \"chainName\", \"$1\", \"index\", \"(.*?).tx\")) by (chainName) "
    },
    {
     "expr": "sum(label_replace(delta(elasticsearch_indices_docs_primary{namespace=\"search\", index=~\".*.tx\"}[24h]), \"chainName\", \"$1\", \"index\", \"(.*?).tx\")) by (chainName) "
    },
    {
     "expr": "sum(label_replace(elasticsearch_indices_docs_primary{namespace=\"search\", index=~\".*.contract_summary\"}, \"chainName\", \"$1\", \"index\", \"(.*?).contract_summary\")) by (chainName) "
    },
    {
     "expr": "sum(label_replace(delta(elasticsearch_indices_docs_primary{namespace=\"search\", index=~\".*.contract_summary\"}[24h]), \"chainName\", \"$1\", \"index\", \"(.*?).contract_summary\")) by (chainName) "
    },
    {
     "expr": "sum(label_replace(elasticsearch_indices_store_size_bytes_primary{namespace=\"search\"}, \"chainName\", \"$1\", \"index\", \"(.*)[.].*\")) by (chainName) "
    }
   ]
  }
 ]
}