# Elassandra Service
apiVersion: v1
kind: Service
metadata:
  name: elassandra
  namespace: search
  labels:
    monitoring: elassandra-monitor
spec:
  clusterIP: None
  ports:
  - name: cql
    port: 9042
  - name: metrics
    port: 8080
    targetPort: 8080
  - name: elastic-http
    port: 9200
  - name: elastic-intra
    port: 9300
  selector:
    app: elassandra
---

# Elassandra StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elassandra
  namespace: search
spec:
  serviceName: elassandra
  replicas: 5
  selector:
    matchLabels:
      app: elassandra
  template:
    metadata:
      namespace: search
      labels:
        app: elassandra
    spec:
      containers:
      - name: elassandra
        image: cybernode/elassandra:5.5.0.19
        ports:
        - containerPort: 7000
          name: intra-node
        - containerPort: 7001
          name: tls-intra-node
        - containerPort: 7199
          name: jmx
        - containerPort: 9042
          name: cql
        - containerPort: 9200
          name: elastic-http
          protocol: TCP
        - containerPort: 9300
          name: elastic-intra
          protocol: TCP
        resources:
          requests:
            cpu: "3.5"
            memory: "20Gi"
          limits:
            cpu: "3.5"
            memory: "20Gi"
        securityContext:
          capabilities:
            add:
              - IPC_LOCK
              - SYS_RESOURCE
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "PID=$(pidof java) && kill $PID && while ps -p $PID > /dev/null; do sleep 1; done"]
        env:
          - name: CASSANDRA_NUM_TOKENS
            value: "16"
          - name: CASSANDRA_SEEDS
            value: "elassandra-0.elassandra.search.svc.cluster.local"
          - name: CASSANDRA_CLUSTER_NAME
            value: "CYBER_SEARCH"
          - name: CASSANDRA_DC
            value: "DC1"
          - name: CASSANDRA_AUTO_BOOTSTRAP
            value: "true"
          - name: JVM_OPTS
            value: -Xmx5g -Xms5g -XX:+ExitOnOutOfMemoryError
          - name: CASSANDRA_ENDPOINT_SNITCH
            value: GossipingPropertyFileSnitch
          - name: POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        volumeMounts:
        - name: elassandra-data
          mountPath: /var/lib/cassandra
      - name: cassandra-exporter
        image: criteord/cassandra_exporter:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          requests:
            cpu: "0.1"
            memory: "300Mi"
          limits:
            cpu: "0.1"
            memory: "300Mi"
  volumeClaimTemplates:
  - metadata:
      name: elassandra-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1200Gi
      storageClassName: fast