
# Kafka Data Volume Claim
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: kafka-broker-claim0
  namespace: search
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
---

# Kafka Service
apiVersion: v1
kind: Service
metadata:
  name: kafka-broker
  namespace: search
spec:
  ports:
  - name: "transport"
    port: 9092
    targetPort: 9092
  - name: "jmx"
    port: 1099
    targetPort: 1099
  selector:
    app: kafka-broker
---

# Kafka Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: search
  name: kafka-broker
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: search
      labels:
        app: kafka-broker
    spec:
      containers:
      - env:
        - name: KAFKA_ADVERTISED_LISTENERS
          value: PLAINTEXT://kafka-broker:9092
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_DELETE_TOPIC_ENABLE
          value: "true"
        - name: KAFKA_JMX_PORT
          value: "1099"
        - name: KAFKA_LOG4J_ROOT_LOGLEVEL
          value: WARN
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
          value: "1"
        - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo:2181
        - name: KAFKA_MESSAGE_MAX_BYTES
          value: "15728640"
        - name: KAFKA_REPLICA_FETCH_MAX_BYTES
          value: "15728640"
        image: confluentinc/cp-kafka:4.0.0-3
        name: kafka-broker
        ports:
        - containerPort: 9092
        - containerPort: 1099
        resources:
          requests:
            cpu: "1.5"
            memory: "15Gi"
          limits:
            cpu: "2"
            memory: "20Gi"
        volumeMounts:
        - mountPath: /var/lib/kafka/data
          name: kafka-broker-claim0
          subPath: data
      restartPolicy: Always
      volumes:
      - name: kafka-broker-claim0
        persistentVolumeClaim:
          claimName: kafka-broker-claim0