# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: search
  name: kafka-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: search
      labels:
        app: kafka-manager
    spec:
      containers:
      - env:
        - name: ZK_HOSTS
          value: zoo:2181
        image: hlebalbau/kafka-manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
        resources:
          requests:
            cpu: "0.1"
            memory: "1Gi"
          limits:
            cpu: "0.2"
            memory: "2Gi"
        name: kafka-manager
      restartPolicy: Always