# Service
apiVersion: v1
kind: Service
metadata:
  name: search-api
  namespace: search
  labels:
    monitoring: default-monitor
spec:
  type: LoadBalancer
  ports:
  - name: "web"
    port: 80
    targetPort: 8080
  selector:
    app: search-api
---

# Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: search
  name: search-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: search
      labels:
        app: search-api
    spec:
      containers:
      - env:
        - name: CASSANDRA_HOSTS
          value: elassandra
        - name: CS_LOG_LEVEL
          value: INFO
        - name: CORS_ALLOWED_ORIGINS
          value: "*"
        - name: JAVA_OPTS
          value: -Xms2g -Xmx2g
        image: cybernode/search-api:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "0.5"
            memory: "2.5Gi"
          limits:
            cpu: "1"
            memory: "2.5Gi"
        ports:
        - containerPort: 8080
        name: search-api
      restartPolicy: Always