# Service
apiVersion: v1
kind: Service
metadata:
  name: search-api
  namespace: search
  labels:
    monitoring: default-monitor
spec:
  type: LoadBalancer
  ports:
  - name: "web"
    port: 80
    targetPort: 8080
  selector:
    app: search-api
---

# Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: search
  name: search-api
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: search
      labels:
        app: search-api
    spec:
      containers:
      - env:
        - name: CASSANDRA_HOSTS
          value: elassandra
        - name: CS_LOG_LEVEL
          value: INFO
        - name: CORS_ALLOWED_ORIGINS
          value: "*"
        image: cybernode/search-api:0.2.7
        ports:
        - containerPort: 8080
        name: search-api
      restartPolicy: Always