
# Use 'NAME=eth CHAIN_NAME=ETHEREUM envsubst < pump.yaml | kubectl apply -f -' command
# Use 'NAME=etc CHAIN_NAME=ETHEREUM_CLASSIC envsubst < pump.yaml | kubectl apply -f -' command

# Pump Service (should expose metrics)
apiVersion: v1
kind: Service
metadata:
  name: pump-${NAME}
  namespace: search
  labels:
    monitoring: default-monitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: pump-${NAME}
---

# Pump Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: search
  name: pump-${NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: search
      labels:
        app: pump-${NAME}
    spec:
      containers:
      - env:
        - name: CHAIN_FAMILY
          value: ETHEREUM
        - name: CHAIN_NAME
          value: ${CHAIN_NAME}
        - name: CHAIN_NODE_URL
          value: http://parity-${NAME}.chains.svc:8545
        - name: CS_LOG_LEVEL
          value: INFO
        - name: KAFKA_BROKERS
          value: kafka:9092
        - name: WITH_MEMPOOL
          value: "true"
        - name: STACK_CACHE_SIZE
          value: "1000"
        - name: JAVA_OPTS
          value: -Xms4g -Xmx4g
        image: cybernode/chain-pump-ethereum:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2"
            memory: "5Gi"
          limits:
            cpu: "2"
            memory: "5Gi"
        ports:
        - containerPort: 8080
        name: pump-${NAME}
      restartPolicy: Always