{
 "title": "Trades dashboard",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Trades count (24h)",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 10, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(increase(trade_count_total[24h]))"
    }
   ]
  },
  {
   "title": "Trades per second",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(trade_count_total[1m])) by (exchange)",
     "legendFormat": "{{exchange}}"
    }
   ]
  },
  {
   "title": "Trade latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    { "expr": "trade_latency_seconds", "legendFormat": "{{exchange}}" }
   ]
  }
 ]
}