{
 "title": "Cyber_node",
 "tags": [
  "node_exporter",
  "cyberd",
  "gaia",
  "docker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "Hardware stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System runtime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - node_boot_time_seconds{instance=~\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "CPU cores",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(count(node_cpu_seconds_total{instance=~\"localhost:9100\", mode='system'}) by (cpu))"
    }
   ]
  },
  {
   "title": "CPU Usage rate（5m）",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=~\"localhost:9100\",mode=\"idle\"}[5m])) * 100)"
    }
   ]
  },
  {
   "title": "CPU iowait（5m）",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 7, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(irate(node_cpu_seconds_total{instance=~\"localhost:9100\",mode=\"iowait\"}[5m])) * 100"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"localhost:9100\"} / (node_memory_MemTotal_bytes{instance=~\"localhost:9100\"})))* 100"
    }
   ]
  },
  {
   "title": "Currently open file descriptor",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"localhost:9100\"}"
    }
   ]
  },
  {
   "title": "Free space for each partition",
   "type": "table-old",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "targets": [
    {
     "expr": "node_filesystem_avail_bytes {instance=~'localhost:9100',fstype=~\"ext4|xfs\"}"
    },
    {
     "expr": "100.0 - 100.0 * ((node_filesystem_avail_bytes{fstype=\"ext4\",instance=\"localhost:9100\",mountpoint=\"/\"}) / (node_filesystem_size_bytes{fstype=\"ext4\",instance=\"localhost:9100\",mountpoint=\"/\"}))"
    }
   ]
  },
  {
   "title": "Total memory",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"localhost:9100\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU average load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{job=\"node_exporter\",mode=\"idle\"}[5m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RAM usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 5 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"localhost:9100\"} - node_memory_MemAvailable_bytes{instance=~\"localhost:9100\"}",
     "legendFormat": "{{instance}}_Used"
    }
   ]
  },
  {
   "title": "Disk space used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100.0 * ((node_filesystem_avail_bytes{device=\"/dev/md2\",fstype=\"ext4\",instance=\"localhost:9100\",job=\"node_exporter\",mountpoint=\"/\"} / 1000 / 1000 ) / (node_filesystem_size_bytes{device=\"/dev/md2\",fstype=\"ext4\",instance=\"localhost:9100\",job=\"node_exporter\",mountpoint=\"/\"}  / 1024 / 1024))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  },
  {
   "title": "Hardware temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 5 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "node_hwmon_temp_celsius{chip=\"platform_coretemp_0\",instance=\"localhost:9100\",sensor=\"temp2\"}\t",
     "legendFormat": "{{chip}}"
    }
   ]
  },
  {
   "title": "Download rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_receive_bytes_total{instance=~'localhost:9100',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_in download"
    }
   ]
  },
  {
   "title": "Upload rate",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 11 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "irate(node_network_transmit_bytes_total{instance=~'localhost:9100',device!~'tap.*|veth.*|br.*|docker.*|virbr*|lo*'}[5m])*8",
     "legendFormat": "{{instance}}_{{device}}_out upload"
    }
   ]
  },
  {
   "title": "TCP Connection situation",
   "type": "graph",
   "description": "CurrEstab - number of TCP connections with current state of ESTABLISHED or CLOSE-WAIT\n\nActiveOpens - TCP average connections that have been converted from the CLOSED state to the SYN-SENT state (within 1 minute)\n\nPassiveOpens - TCP average connections that have been converted from the LISTEN state to the SYN-RCVD state (within 1 minute)\n\nTCP_alloc - the number of TCP sockets that have been allocated (established, applied to sk_buff)\n\nTCP_inuse - the number of TCP sockets being used (listening)\n\nTCP_tw - number of TCP connections waiting to be closed",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'localhost:9100'}",
     "legendFormat": "Conn_Established"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'localhost:9100'}",
     "legendFormat": "TCP_socket_Time_Wait"
    },
    {
     "expr": "irate(node_netstat_Tcp_ActiveOpens{instance=~'localhost:9100'}[1m])",
     "legendFormat": "Active_Open"
    },
    {
     "expr": "irate(node_netstat_Tcp_PassiveOpens{instance=~'localhost:9100'}[1m])",
     "legendFormat": "PassiveOpens"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'localhost:9100'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "node_sockstat_TCP_inuse{instance=~'localhost:9100'}",
     "legendFormat": "TCP_inuse"
    }
   ]
  },
  { "title": "Cyberd stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Last Block",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_height{instance=\"localhost:26660\"}"
    }
   ]
  },
  {
   "title": "P2P peers ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_p2p_peers{instance=\"localhost:26660\"}\t",
     "legendFormat": "peers"
    }
   ]
  },
  {
   "title": "Active validators",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_validators{instance=\"localhost:26660\"}"
    }
   ]
  },
  {
   "title": "Sync status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_fast_syncing{chain_id=\"euler-6\",instance=\"localhost:26660\",job=\"Cyberd\"}"
    }
   ]
  },
  {
   "title": "Total # commited TX's ",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_total_txs{instance=\"localhost:26660\"}"
    }
   ]
  },
  {
   "title": "Block size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tendermint_consensus_block_size_bytes{instance=\"localhost:26660\"}"
    }
   ]
  },
  {
   "title": "Block time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_block_interval_seconds_sum{instance=\"localhost:26660\"}/tendermint_consensus_block_interval_seconds_count{instance=\"localhost:26660\"}",
     "legendFormat": "Block_time"
    }
   ]
  },
  {
   "title": "Block counter",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "tendermint_consensus_height{instance=\"localhost:26660\"}",
     "legendFormat": "Block_time"
    }
   ]
  },
  { "title": "Docker stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Containers Running",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(rate(container_last_seen{name=~\".+\"}[30s]))"
    }
   ]
  },
  {
   "title": "Disk used",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 5, "x": 2, "y": 26 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=~\".+\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "CPU Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 7, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[30s])) by (name) * 100",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Memory Usage per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Received Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{name=~\".+\"}[1m])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Sent Network Traffic per Container",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{name=~\".+\"}[30s])) by (name)",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}