apiVersion: v1
kind: List
items:

# Service
- apiVersion: v1
  kind: Service
  metadata:
    name: bitcoind-btc-testnet
    namespace: chains
  spec:
    ports:
    - name: "8332"
      port: 8332
      targetPort: 18332
    selector:
      chain: bitcoind-btc-testnet

# Deployment
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: bitcoind-btc-testnet
    namespace: chains
  spec:
    replicas: 1
    strategy:
      type: Recreate
    selector:
      matchLabels:
        chain: bitcoind-btc-testnet
    template:
      metadata:
        labels:
          chain: bitcoind-btc-testnet
      spec:
        containers:
        - args:
          - -testnet
          - -server
          - -rest
          - -txindex
          - -printtoconsole
          - -debug=rpc,http
          - -rpcclienttimeout=220
          - -rpcthreads=128
          - -rpcpassword=cyber
          - -rpcuser=cyber
          - -rpcallowip=0.0.0.0/0
          image: ruimarinho/bitcoin-core:0.16.0
          name: bitcoind-btc-testnet-pod
          resources:
            requests:
              cpu: "2"
              memory: "10Gi"
            limits:
              cpu: "2"
              memory: "12Gi"
          ports:
          - containerPort: 18332
          volumeMounts:
          - mountPath: /home/bitcoin/.bitcoin
            name: bitcoind-btc-testnet-claim0
        restartPolicy: Always
        volumes:
        - name: bitcoind-btc-testnet-claim0
          persistentVolumeClaim:
            claimName: bitcoind-btc-testnet-claim0

# Volume Claim
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: bitcoind-btc-testnet-claim0
    namespace: chains
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 200Gi
    storageClassName: fast