# Service
apiVersion: v1
kind: Service
metadata:
  name: abc-bth
  namespace: chains
spec:
  ports:
  - name: "8332"
    port: 8332
    targetPort: 8332
  selector:
    chain: abc-bth
---

# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: abc-bth
  namespace: chains
spec:
  serviceName: abc-bth
  replicas: 1
  selector:
    matchLabels:
      chain: abc-bth
  template:
    metadata:
      labels:
        chain: abc-bth
    spec:
      restartPolicy: Always
      containers:
      - args:
        - -server
        - -rest
        - -txindex
        - -printtoconsole
        - -debug=rpc,http
        - -rpcclienttimeout=220
        - -rpcthreads=128
        - -rpcallowip=0.0.0.0/0
        image: zquestz/bitcoin-abc
        name: abc-bth-pod
        command: ["bitcoind"]
        resources:
          requests:
            cpu: "3"
            memory: "15Gi"
          limits:
            cpu: "3"
            memory: "20Gi"
        ports:
        - containerPort: 8332
        volumeMounts:
        - mountPath: /data
          name: abc-bth-data
  volumeClaimTemplates:
  - metadata:
      name: abc-bth-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage:  500Gi
      storageClassName: fast