
# Service
apiVersion: v1
kind: Service
metadata:
  name: parity-eth-kovan
  namespace: chains
spec:
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  selector:
    chain: parity-eth-kovan
---

# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: parity-eth-kovan-deployment
  namespace: chains
spec:
  serviceName: parity-eth-kovan
  replicas: 1
  selector:
    matchLabels:
      chain: parity-eth-kovan
  template:
    metadata:
      labels:
        chain: parity-eth-kovan
    spec:
      restartPolicy: Always
      containers:
      - args:
        - --db-path
        - /cyberdata
        - --jsonrpc-hosts
        - all
        - --jsonrpc-interface
        - all
        - --jsonrpc-threads
        - "16"
        - --chain
        - kovan
        - --tracing
        - "on"
        image: parity/parity:stable
        name: parity-eth-kovan-pod
        resources:
          requests:
            cpu: "1"
            memory: "10Gi"
          limits:
            cpu: "2"
            memory: "15Gi"
        ports:
        - containerPort: 8545
        volumeMounts:
        - mountPath: /cyberdata
          name: parity-eth-kovan-data
  volumeClaimTemplates:
  - metadata:
      name: parity-eth-kovan-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage:  50Gi
      storageClassName: fast
