
# Service
apiVersion: v1
kind: Service
metadata:
  name: parity-eth
  namespace: chains
spec:
  ports:
  - name: "8545"
    port: 8545
    targetPort: 8545
  - name: "8546"
    port: 8546
    targetPort: 8546
  selector:
    chain: parity-eth
---

# StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: parity-eth-deployment
  namespace: chains
spec:
  serviceName: parity-eth
  replicas: 1
  selector:
    matchLabels:
      chain: parity-eth
  template:
    metadata:
      labels:
        chain: parity-eth
    spec:
      restartPolicy: Always
      containers:
      - args:
        - --db-path
        - /cyberdata
        - --jsonrpc-hosts
        - all
        - --jsonrpc-interface
        - all
        - --ws-hosts
        - all
        - --ws-interface
        - all
        - --jsonrpc-threads
        - "16"
        - --tracing
        - "on"
        image: parity/parity:stable
        name: parity-eth-pod
        resources:
          requests:
            cpu: "3"
            memory: "20Gi"
          limits:
            cpu: "3"
            memory: "25Gi"
        ports:
        - containerPort: 8545
          name: json-rpc
        - containerPort: 8546
          name: ws
        volumeMounts:
        - mountPath: /cyberdata
          name: parity-eth-data
  volumeClaimTemplates:
  - metadata:
      name: parity-eth-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage:  200Gi
      storageClassName: fast
