{
 "title": "Elassandra Monitoring",
 "tags": [ "elassandra" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "service", "query": "search,  markets" },
   {
    "name": "cluster",
    "query": "label_values(elasticsearch_cluster_health_status,cluster)"
   }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "elasticsearch_cluster_health_number_of_nodes{cluster=\"$cluster\", namespace=\"$service\"}"
    }
   ]
  },
  {
   "title": "Total Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_filesystem_data_size_bytes{cluster=\"$cluster\", namespace=\"$service\"}) - sum(elasticsearch_filesystem_data_available_bytes{cluster=\"$cluster\", namespace=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Docs Count",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_docs_primary{namespace=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total Docs Size",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(elasticsearch_indices_store_size_bytes_primary{namespace=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total RAM Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"elassandra.*\", namespace=\"$service\"})"
    }
   ]
  },
  {
   "title": "Total CPU Used",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", pod_name=~\"elassandra.*\", namespace=\"$service\"}[1h]))"
    }
   ]
  },
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Elassandra Available Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{persistentvolumeclaim=~\"elassandra.*\", exported_namespace=\"$service\"}",
     "legendFormat": " {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Elassandra RAM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 4 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{pod_name=~\"elassandra.*\", namespace=\"$service\"}) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  {
   "title": "Elassandra Network IO Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\", pod_name=~\"elassandra.*\", namespace=\"$service\"}[1m])) by (pod_name)",
     "legendFormat": "-> {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\", pod_name=~\"elassandra.*\", namespace=\"$service\"}[1m])) by (pod_name)",
     "legendFormat": "<- {{pod_name}}"
    }
   ]
  },
  {
   "title": "Elassandra CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", pod_name=~\"elassandra.*\", namespace=\"$service\"}[1m])) by (pod_name)",
     "legendFormat": "{{pod_name}}"
    }
   ]
  },
  { "title": "Elastic Perfomance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Documents query rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "query calls/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_search_query_total{cluster=\"$cluster\", namespace=\"$service\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents indexed rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 6, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "index calls/s" }
   ],
   "targets": [
    {
     "expr": "irate(elasticsearch_indices_indexing_index_total{cluster=\"$cluster\", namespace=\"$service\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents deleted rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_docs_deleted{cluster=\"$cluster\", namespace=\"$service\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Documents merged rate",
   "type": "graph",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 17 },
   "yaxes": [
    { "format": "short", "label": "Documents/s" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total{cluster=\"$cluster\", namespace=\"$service\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Query time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_search_query_time_seconds{cluster=\"$cluster\", namespace=\"$service\"}[10m]) ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Indexing time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 28 },
   "yaxes": [
    { "format": "ms", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_indexing_index_time_seconds_total{cluster=\"$cluster\", namespace=\"$service\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Merging time",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 28 },
   "yaxes": [
    { "format": "s", "label": "Time" }
   ],
   "targets": [
    {
     "expr": "rate(elasticsearch_indices_merges_total_time_seconds_total{cluster=\"$cluster\", namespace=\"$service\"}[10m])",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Cassandra Perfomance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "Write Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "writes/s" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(cassandra_stats{namespace=\"$service\",name=~\"org:apache:cassandra:metrics:table:.*:.*:writelatency:oneminuterate\"}, \"table\", \"$1\", \"name\", \".+:.*:(.+?):writelatency:oneminuterate\")) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{ table }}"
    }
   ]
  },
  {
   "title": "Read rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "yaxes": [
    { "format": "short", "label": "writes/s" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(cassandra_stats{namespace=\"$service\",name=~\"org:apache:cassandra:metrics:table:.*:.*:readlatency:oneminuterate\"}, \"table\", \"$1\", \"name\", \".+:.*:(.+?):readlatency:oneminuterate\")) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{ table }}"
    }
   ]
  },
  {
   "title": "Write Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(cassandra_stats{namespace=\"$service\",name=~\"org:apache:cassandra:metrics:table:.*:.*:writelatency:98thpercentile\"}, \"table\", \"$1\", \"name\", \".+:(.*?):writelatency:.+\")) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{ table }}"
    }
   ]
  },
  {
   "title": "Read Latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "sum(label_replace(cassandra_stats{namespace=\"$service\",name=~\"org:apache:cassandra:metrics:table:.*:.*:readlatency:98thpercentile\"}, \"table\", \"$1\", \"name\", \".+:(.*?):readlatency:.+\")) by (keyspace, table)",
     "legendFormat": "{{keyspace}}.{{ table }}"
    }
   ]
  },
  { "title": "Documents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 55 } },
  {
   "title": "Documents Count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_docs_primary{namespace=\"$service\"}",
     "legendFormat": "{{index}}"
    }
   ]
  },
  {
   "title": "Total Index Size",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 56 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "elasticsearch_indices_store_size_bytes_primary{namespace=\"$service\"}",
     "legendFormat": "{{index}}"
    }
   ]
  }
 ]
}