{
 "title": "Nodes Metrics",
 "tags": [ "cluster" ],
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "machine",
    "query": "label_values(machine_memory_bytes,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "All Nodes Usage",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(machine_memory_bytes) by (instance)"
    },
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\"}) by (instance) / sum(machine_memory_bytes) by (instance)"
    },
    {
     "expr": "sum(machine_cpu_cores) by (instance)"
    },
    {
     "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\"}[1m])) by (instance) / sum(machine_cpu_cores) by (instance)"
    },
    {
     "expr": "sum (rate(container_network_receive_bytes_total{image!=\"\"}[1m])) by (instance)"
    },
    {
     "expr": "sum (rate(container_network_transmit_bytes_total{image!=\"\"}[1m])) by (instance)"
    },
    {
     "expr": "count(sum(container_cpu_usage_seconds_total{name!=\"\", pod_name!~\"kube.*|fluentd.*|l7.*.*|heapster.*|.*exporter.*\"}) by (pod_name, instance)) by (instance)"
    }
   ]
  },
  { "title": "Machine $machine", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 }, "repeat": "machine" },
  {
   "title": "Machine Pods",
   "type": "table",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{name!=\"\", instance=~\"$machine\", pod_name!~\"kube.*|fluentd.*|l7.*.*|heapster.*|.*exporter.*\"}[1m])) by (pod_name, namespace)"
    },
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{name!=\"\", instance=~\"$machine\", pod_name!~\"kube.*|fluentd.*|l7.*.*|heapster.*|.*exporter.*\"}[1h])) by (pod_name, namespace)"
    },
    {
     "expr": "sum (container_memory_usage_bytes{name!=\"\", instance=~\"$machine\", pod_name!~\"kube.*|fluentd.*|l7.*.*|heapster.*|.*-exporter.*\"}) by (pod_name, namespace)"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_cpu_cores{instance=~\"$machine\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Used CPU",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 14 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name!=\"\",instance=~\"$machine\"}[1m]))",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 17 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "machine_memory_bytes{instance=~\"$machine\"}"
    }
   ]
  },
  {
   "title": "Used RAM",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 17 },
   "format": "decbytes",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{name!=\"\",instance=~\"$machine\"})"
    }
   ]
  }
 ]
}