{
 "title": "Storage Monitoring",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15s",
 "templating": {
  "list": [
   { "name": "Namespace", "query": "label_values(namespace)" }
  ]
 },
 "panels": [
  { "title": "Elassandra", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Elassandra Available Space",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "kubelet_volume_stats_available_bytes{exported_namespace=~\"^$Namespace$\",persistentvolumeclaim=~\"elassandra.*\"}",
     "legendFormat": "[{{exported_namespace}}] {{persistentvolumeclaim}}"
    }
   ]
  },
  {
   "title": "Elassandra CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\", namespace=~\"^$Namespace$\", pod_name=~\"elassandra.*\"}[1m])) by (pod_name, namespace)",
     "legendFormat": "[{{namespace}}] {{pod_name}}"
    }
   ]
  },
  {
   "title": "Elassandra RAM Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\", namespace=~\"^$Namespace$\", pod_name=~\"elassandra.*\"}[1m])) by (pod_name, namespace)",
     "legendFormat": "[{{namespace}}] {{pod_name}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\", pod_name=~\"elassandra.*\"}[1m])) by (pod_name, namespace)",
     "legendFormat": "IN [{{namespace}}] {{pod_name}}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",namespace=~\"^$Namespace$\", pod_name=~\"elassandra.*\"}[1m])) by (pod_name, namespace)",
     "legendFormat": "OUT [{{namespace}}] {{pod_name}}"
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Available Space",
     "type": "graph",
     "gridPos": { "h": 7, "w": 16, "x": 0, "y": 27 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "expr": "kubelet_volume_stats_available_bytes{exported_namespace=~\"search|markets\",persistentvolumeclaim=~\"kafka.*\"}",
       "legendFormat": "[{{exported_namespace}}] {{persistentvolumeclaim}}"
      }
     ]
    }
   ]
  }
 ]
}