
# Use 'NAME=btc CHAIN_NAME=BITCOIN envsubst < dump-cassandra.yaml | kubectl apply -f -' command
# Use 'NAME=bth CHAIN_NAME=BITCOIN_CASH envsubst < dump-cassandra.yaml | kubectl apply -f -' command

# Dump Service (should expose metrics)
apiVersion: v1
kind: Service
metadata:
  name: dump-cassandra-${NAME}
  namespace: search
  labels:
    monitoring: default-monitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: dump-cassandra-${NAME}
---

# Dump Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: search
  name: dump-cassandra-${NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dump-cassandra-${NAME}
  template:
    metadata:
      namespace: search
      labels:
        app: dump-cassandra-${NAME}
    spec:
      containers:
      - env:
        - name: CHAIN_FAMILY
          value: BITCOIN
        - name: CHAIN_NAME
          value: ${CHAIN_NAME}          
        - name: CASSANDRA_HOSTS
          value: elassandra
        - name: CS_LOG_LEVEL
          value: INFO
        - name: KAFKA_BROKERS
          value: kafka:9092
        - name: JAVA_OPTS
          value: -Xms2000m -Xmx2000m
        - name: KAFKA_LISTENER_MAX_POLL_RECORDS
          value: "100"
        - name: CASSANDRA_MAX_CONNECTIONS_LOCAL
          value: "32768"
        - name: CASSANDRA_MAX_CONNECTIONS_REMOTE
          value: "32768"
        image: cybernode/chain-dump-cassandra-bitcoin:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "3"
            memory: "2.5Gi"
          limits:
            cpu: "3"
            memory: "2.5Gi"
        ports:
        - containerPort: 8080
        name: dump-cassandra-${NAME}
      restartPolicy: Always