
# Use 'NAME=btc CHAIN_NAME=BITCOIN CHAIN_URL=cyber:cyber@bitcoind-btc envsubst < pump.yaml | kubectl apply -f -' command
# Use 'NAME=bth CHAIN_NAME=BITCOIN_CASH CHAIN_URL=bitcoin:password@abc-bth envsubst < pump.yaml | kubectl apply -f -' command

# Pump Service (should expose metrics)
apiVersion: v1
kind: Service
metadata:
  name: pump-${NAME}
  namespace: search
  labels:
    monitoring: default-monitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: pump-${NAME}
---

# Pump Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: search
  name: pump-${NAME}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: pump-${NAME}
  template:
    metadata:
      namespace: search
      labels:
        app: pump-${NAME}
    spec:
      containers:
      - env:
        - name: CHAIN_FAMILY
          value: BITCOIN
        - name: CHAIN_NAME
          value: ${CHAIN_NAME}          
        - name: CHAIN_NODE_URL
          value: http://${CHAIN_URL}.chains.svc:8332
        - name: CS_LOG_LEVEL
          value: INFO
        - name: KAFKA_BROKERS
          value: kafka:9092
        - name: JAVA_OPTS
          value: -Xms17g -Xmx17g
        - name: BITCOIN_TX_OUTS_CACHE_HEAP_SIZE
          value: "8"
        - name: BTC_TX_DOWNLOAD_MAX_CONCURRENCY
          value: "10"
        - name: WITH_MEMPOOL
          value: "true"
        image: cybernode/chain-pump-bitcoin:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2.5"
            memory: "22Gi"
          limits:
            cpu: "2.5"
            memory: "25Gi"
        ports:
        - containerPort: 8080
        name: pump-${NAME}
      restartPolicy: Always