# Pump Service (should expose metrics)
apiVersion: v1
kind: Service
metadata:
  name: pump-btc
  namespace: search
  labels:
    monitoring: default-monitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: pump-btc
---

# Pump Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: search
  name: pump-btc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: search
      labels:
        app: pump-btc
    spec:
      containers:
      - env:
        - name: CHAIN
          value: BITCOIN
        - name: CHAIN_NODE_URL
          value: http://cyber:cyber@bitcoind-btc.chains.svc:8332
        - name: CS_LOG_LEVEL
          value: INFO
        - name: KAFKA_BROKERS
          value: kafka-broker:9092
        - name: JAVA_OPTS
          value: -Xms9g -Xmx9g
        image: cybernode/chain-pump-bitcoin:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "1.5"
            memory: "10Gi"
          limits:
            cpu: "2"
            memory: "12Gi"
        ports:
        - containerPort: 8080
        name: pump-btc
      restartPolicy: Always