# Pump Service (should expose metrics)
apiVersion: v1
kind: Service
metadata:
  name: pump-btc
  namespace: search
  labels:
    monitoring: default-monitor
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: pump-btc
---

# Pump Deployment
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: search
  name: pump-btc
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      namespace: search
      labels:
        app: pump-btc
    spec:
      containers:
      - env:
        - name: CHAIN_FAMILY
          value: BITCOIN
        - name: CHAIN_NODE_URL
          value: http://cyber:cyber@bitcoind-btc.chains.svc:8332
        - name: CS_LOG_LEVEL
          value: INFO
        - name: KAFKA_BROKERS
          value: kafka-broker:9092
        - name: JAVA_OPTS
          value: -Xms15g -Xmx15g
        - name: BITCOIN_TX_OUTS_CACHE_HEAP_SIZE
          value: "10"
        - name: BTC_TX_DOWNLOAD_MAX_CONCURRENCY
          value: "10"
        image: cybernode/chain-pump-bitcoin:latest
        imagePullPolicy: Always
        resources:
          requests:
            cpu: "2.5"
            memory: "20Gi"
          limits:
            cpu: "2.5"
            memory: "20Gi"
        ports:
        - containerPort: 8080
        name: pump-btc
      restartPolicy: Always